### ISSUE TITLE
MC protocol is not recognized in the ipfs webui

### ISSUE THREAD

**Issue by D4ryl00** [berty/berty#2019]
Error when loading the Ipfs Webui:
![image](https://user-images.githubusercontent.com/13605410/83897518-f86a5b80-a755-11ea-9e86-7c415f338b78.png)

**To reproduce**
1) Put the mobile in airplane mode (increase the chance to reproduce this issue)
2) Start `Berty` app
3) Go to the Ipfs Webui

A big cross is displayed, but if you run the webui in dev mode, you got those error details.

**Comment by aeddi** [comment]
The reason is most likely that MultipeerConnectivity's MultiAddress is not declared in the IPFS JS packages.

When the transport will be ready, we will make sure to open PRs on the related repos, including on this one: https://github.com/multiformats/multiaddr/blob/master/protocols.csv

In the meantime we can fork the webui repo or add manually a JS file that declares the MultiAddr.
Not a priority for the moment, we'll see in a couple of weeks ;)

**Comment by moul** [comment]
Is this issue still relevant, or can we close it?
