### ISSUE TITLE
Error when running "go install" in cmd directory.

### ISSUE THREAD

**Issue by cbracketdash** [berty/berty#3056]
I just tried installing berty with "go install" but after a while, I get the error: 
```
# github.com/mattn/go-sqlite3 
cgo: exec /missing-cc: exec: "/missing-cc": file does not exist
```

**Comment by cbracketdash** [comment]
friendly bump :)

**Comment by cbracketdash** [comment]
bump...

**Comment by cbracketdash** [comment]
bump

**Comment by cbracketdash** [comment]
bumpp

**Comment by LFGaming** [comment]
Have you tried asking in the [Berty Discord](https://crpt.fyi/berty-discord)? They are often quite fast there, that may be a good choice to try.

**Comment by gfanton** [comment]
Hello @cbracketdash, sorry for the response time, we didn't have an effective process or notification system set up to handle issues and PRs from the community. From now on we should be much more responsive.

Can you give us more context on your problem? (OS Version, Go version, etc...)

**PS.** Use `make install` command (inside the go folder) instead of `go install`
**PS2.** If you are on go 1.16, try to update to the latest commit from master, it should work since https://github.com/berty/berty/pull/3106,
