### ISSUE TITLE
Generate preview builds of mobile app

### ISSUE THREAD

**Issue by link2xt** [berty/berty#3067]
I would like to try this app in whatever state it is, but don't want to compile it myself. Maybe even before you open beta (https://github.com/berty/berty/issues/2227), start providing alpha builds without advertising them too much outside of GitHub?

Would be cool if you uploaded APKs to releases. Maybe use a GitHub action to build APKs for each PR or tag, like here: https://github.com/deltachat/deltachat-android/pull/1773

**Comment by programmin1** [comment]
Yeah, it takes gigabytes of android+ndk to even start.

I tried but I get an error on "make android.debug"

berty/js/android/.gomobile-cache/android/src/main/jniLibs/armeabi-v7a/libgojni.so ./gobind failed: exit status 2

Like it says in the go mobile "Gophers are doing experiments" - https://github.com/golang/mobile
So it would probably be a good idea to do so once the build can actually build predictably.

**Comment by aeddi** [comment]
Hello,

Sorry for the response time, we didn't have an effective process or notification system set up to handle issues and PRs from the community. From now on we should be much more responsive.

For the moment, the app is not ready, especially the Android version. That's why we haven't set up a preview mechanism yet. We will put one in place when we feel the time is right.

Anyway, you can follow [this guide](https://github.com/berty/berty/tree/master/js#running-the-mobile-apps-for-development) to build the app yourself and if some info is missing or an error occurs, open a dedicated issue with as much info as possible so we can help you and improve the doc.

> Would be cool if you uploaded APKs to releases. Maybe use a GitHub action to build APKs for each PR or tag, like here: deltachat/deltachat-android#1773

Github Actions already build the app versions and push them to our internal platform. It should be possible to install the app by downloading the artifacts available on this Github repo by the way.

> I tried but I get an error on "make android.debug"

Open a detailed issue about it and we will give you a hand. 😉
