### ISSUE TITLE
[BUG]: Long-term outage/blocking of the initially chosen rendezvous server stops Berty from working

### ISSUE THREAD

**Issue by dumblob** [berty/berty#4218]
### Actual Results / Problem

When an agency, network failure, whatsoever (e.g. in case of nation-wide filtering/censorship, war, ...) causes the at-the-first-login-designated rendezvous (turn, ...) server to be unavailable, Berty effectively stops working until the server is reachable again (assuming the peers I communicate with are not in BLE distance nor on the same LAN).

This is unacceptable and catapults Berty from a P2P category to just a de-centralized E2EE category with other ordinary state/agency-controlled messangers (Signal, Threema, Telegram, WhatsApp, ...).

### Expected Results / Possible Fix

I expect Berty to at least immediately and continuously inform the user about this and offer solutions (e.g. a random choice from a huge list of alternative rendezvous servers based on certain criteria - esp. immediate reachability, jurisdiction/legislation similarity, etc.).

Still compared to e.g. Delta Chat, there is no real solution to this. Delta Chat has an enormous advantage here (almost a "guarantee") due to the collateral damage it would cause if anyone decided to block them or even turn them off (gmail, yandex, ...).

### Give use some context

Any screenshots to share?

N/A

Anything else you want to tell us, like your favorite cheese?

The underlying SW libraries Berty uses seem to have pure DHT capability without using any rendezvous servers. This capability has (very) limited functionality (and is naturally very slow) but I still have hopes that it could fully substitute rendezvous servers by default and only if the user has **opted in** then rendezvous servers (incl. Google push notification servers etc.) would be used **in addition** to DHT (not in exchange for) to make message sending snappier.

**Comment by n0izn0iz** [comment]
The DHT is already used in parallel

You can also disable the rendezvous servers in the app UI and only use the DHT if you want

But for a mobile use-case we recommend using the rendezvous servers as it's vastly superior to the DHT for a daily usage

**Comment by aeddi** [comment]
I should add that Berty needs nothing more than the DHT to work.

But for the app to be usable on a daily basis, we add bits of infra that allow for smooth use on mobile:
- p2p-circuit relays to do NAT traversal
- rdvp to make the discovery fast
- replication nodes to provide high availability on messages

All of these are optional but highly recommended on mobile. All of these are also hostable by a third party to be added in the app with the possibility to disable those hosted by Berty.

We also have in mind to make it simple for the user to run his own rdvp / replication node / relay easily, for example: built-in in the future desktop app, as a docker image, as a package for Synology / Qnap NAS, etc.

**Comment by dumblob** [comment]
Thanks for quick answers!

I am glad DHT is used **in parallel** - this information is super important and should be highlighted in readme and documentation.

>You can also disable the rendezvous servers in the app UI and only use the DHT if you want

Interesting, I could not find this option e.g. when creating a new identity. Still I am convinced people shall opt in for (much) faster processing (involving rendezvous/p2p-circuit/rdvp/replication_nodes ) instead of not telling them and expecting them to be experts to ask themself whether it is possible and then finding how actually.

>All of these are also hostable by a third party to be added in the app with the possibility to disable those hosted by Berty.

That is definitely a good starting point! But that is still far from optimum. Namely if I already opted in for fast relay of messages I expect the app to automatically DHT-discover also lists of relay servers other peers are publishing/using and randomly change them very often (perhaps even for each message). I definitely do not expect the app to connect to 1 or just a few well known servers. Moreover I definitely do not expect myself to manually choose which server to use now and which one in a minute from now. Finally I do not want to manually maintain the list of servers myself in some third-party note-taking app but want Berty to show me the current list from DHT peers (which might have thousands of items) and allow me to put some of them on a black list (either individually or according to some filtering rule - e.g. servers probably hosted in a country/state with incompatible jurisdiction).

What do you think?

**Comment by aeddi** [comment]
> Interesting, I could not find this option e.g. when creating a new identity.

You can find it both when you chose to customize Berty during the onboarding and in the settings.
<img width="627" alt="Screenshot 2022-06-27 at 21 16 53" src="https://user-images.githubusercontent.com/5222525/176019009-564a4ef5-cb9e-41f6-8003-4e180b5842cf.png">
<img width="627" alt="Screenshot 2022-06-27 at 21 17 38" src="https://user-images.githubusercontent.com/5222525/176019047-6d98417e-883f-4583-84c5-589fe1b9800a.png">

> Still I am convinced people shall opt in for (much) faster processing (involving rendezvous/p2p-circuit/rdvp/replication_nodes ) instead of not telling them and expecting them to be experts to ask themself whether it is possible and then finding how actually.

It's complicated to summarize the different levels of opt-in / opt-out, especially since UX is constantly evolving as we think, but globally at the start of the app, you have a "default" mode that activates RDVP and relays directly (deactivatable in the settings afterwards).
And in the custom mode, the user has the possibility to directly deactivate these options or to add their own RDVP / relays if they want.
It is precisely because we do not expect all our users to be experts that these options will remain as "opt-out" in the case of the default mode.
Especially since DHT is very poorly suited for mobile use and relays are essential on most cellular connections.

> Namely if I already opted in for fast relay of messages I expect the app to automatically DHT-discover also lists of relay servers other peers are publishing/using and randomly change them very often (perhaps even for each message).

What you describe is not applicable for mobile use. It's already very complicated to create something stable and optimized on mobile with only one relay per session.
Also when you talk about having a thousand connections in parallel, on mobile it's simply impossible. When you launch an IPFS node on iPhone, from about 200 peers connected, some routines of the app start to fail in loop because of a "too many open files" error.
And even before that, the power consumption is way too high, even under a hundred peers. Today, we would like to set up a system to make the application stable with about 30 peers connected.
