### ISSUE TITLE
BLE Mesh?

### ISSUE THREAD

**Issue by RageGamerBoi** [berty/berty#4600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Feature request

If not already implemented, BLE mesh would be an awesome feature.

### Context

For long range offline communication among trusted contacts (but try to prevent MITM attacks, it's a hard problem to solve, but I bet you can do it!)

### Possible implementation

P2P chat but offline.
You would probably need to make another protocol working with the [BLE Mesh standard](https://en.wikipedia.org/wiki/Bluetooth_mesh_networking), or figure out a way to jerry-rig something with IPFS.

**Comment by LFGaming** [comment]
If I understand you correctely then yes a BLE mesh is already in the berty app, you can use ble to send and recieve messages from other people and their phone will send the message to other people in the group if you are not in range but they are.
if you want to read up on it then here is the berty protocol documentation: https://berty.tech/docs/protocol/

**Comment by RageGamerBoi** [comment]
> you can use ble to send and recieve messages from other people and their phone will send the message to other people in the group if you are not in range but they are.

I mean, will it mesh with everybody on Berty.

I’m not talking about a Briar style mesh ex:
![C918314E-2EF3-49DE-B1B4-AF2A88687E79](https://user-images.githubusercontent.com/105567407/221441021-02ba1962-68e6-439d-b7f4-f757b791231c.png)

But more of an IPFS over BLE type thing, where people outside of a group can pass on messages entirely offline as well.

**Comment by RageGamerBoi** [comment]
Taking a look through the docs, it appears this is in the protocol, is it implemented yet?
https://berty.tech/docs/protocol/#direct-transport

**Comment by LFGaming** [comment]
I sadly can not confirm if this is already fully inplemented because my 3rd phone died so i can not try it out at the moment,, will let you know later if i have the posibility to test it.

**Comment by RageGamerBoi** [comment]
Alright. If anyone else can confirm this, it would be appreciated :)

**Comment by LFGaming** [comment]
just tried with 3 iphones and with 2 iphones and an android,, and when everyone has each other in their contacts it does not yet seem to work, so with A,B on and C not the app open,, then a sending something to C, then A closing the app, and C opening the app,, B will not send it to C.
If I tested a wrong thing please let me know and ill retry the test

**Comment by RageGamerBoi** [comment]
Berty takes a while to sync offline (up to 10 minutes from my testing), so leave all 3 apps open.
Then make phones 1 and 2 have a conversation with each other with phone 3 having either in it’s contacts AT ALL (all phones bluetooth only).
Shut down phone 1 and send a message to phone 1 from phone 2
Wait ~10-15 minutes
Shut down phone 2 and power on phone 1
Wait ~10-15 minutes
Did it work?

If it doesn’t, set phone 1 to no internet, just bluetooth, set phone 3 to internet and bluetooth, and set phone 2 to just internet. Then repeat the above steps without shutting down any phones.

**Comment by D4ryl00** [comment]
Our mesh is the same as Briar, so phones will share messages with others who are in the same group of conversation (multimember group or 1v1), and it is already implemented.
If that doesn't work for you, it is probably due to the instability of the BLE driver. The last time I worked on it (more than 1 year), that works fine, but right now I don't have to work on it to check the level of instability and fix it, but it's planned :)

A true mesh layer (where you relay all messages for all Berty users) on Bluetooth is not possible I think with the current level of instability of the Bluetooth stack driver of the various brand phones. Because each brand has its own implementation (with bugs) of the Bluetooth specification, it's often that they can't communicate correctly with each other.
Another point is that Bluetooth starts to lose communication if you have more than 4 connected devices (that can be less with some phones), so if you keep 1 slot to find new phones around you, you have only 3 connection slots remaining to create a mesh (and exchange data.
A last and important thing is that a true mesh will drain the battery of your phone because of the quantity of data transmission.

**Comment by RageGamerBoi** [comment]
Ah, ok makes sense.
A true mesh would definitely require some new hardware (ex. if Meshtastic ever gets a global mesh >80 nodes for instance), and probably only allow text chat.
