### ISSUE TITLE
How to remove a contact

### ISSUE THREAD

**Issue by mp3butcher** [berty/berty#4858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app v2.470.3 

### Feature request

Remove an existing contact.

### Context

I tested to add contact but I can't find a way to remove it

**Comment by jefft0** [comment]
Hello @mp3butcher . There is a feature request to hide a contact https://github.com/berty/berty/issues/4606 . A contact is actually a user group with only two members: You and your contact. For security reasons, Berty doesn't support deleting a contact (or a message) because in a p2p environment it really isn't deleted, so it can give a false sense of security that it's gone.
